### ISSUE TITLE
[Feature request] Optional operations

### ISSUE THREAD

**Issue by honguyenminh** [davidhoang05022009/fedora-post-install-script#1]
Makes the operations optional instead of forcing all operation on the user.

Maybe show a "Select options to run" and a list to select or something similar?

**Comment by hmthien050209** [comment]
Thanks for your feedback.

>Makes the operations optional instead of forcing all operation on the user.
Maybe show a "Select options to run" and a list to select or something similar?

Let see if I can make this feature available in a GUI-based script.

**Comment by honguyenminh** [comment]
Even just show the indexed list of features then ask the user to type the index(es) separated by spaces is fine.

Adding GUI will require additional GUI dependencies, and they're not lightweight.

**Comment by hmthien050209** [comment]
OK, let me update this next week, currently I'm busy.

**Comment by alaireselene** [comment]
> Even just show the indexed list of features then ask the user to type the index(es) separated by spaces is fine.
> 
> Adding GUI will require additional GUI dependencies, and they're not lightweight.

A TUI Interface is better for a simple script. I think 'curses' is a good choice.

**Comment by hmthien050209** [comment]
Currently learning how to use bash script and dialog for this issue.
It could take a long time because I'm going to take some tests at school, maybe finish on January 23rd.

**Comment by hmthien050209** [comment]
I added this feature to the script(migrated the script to shell script) so this issue is closed
