### ISSUE TITLE
Make README actually describe what it does

### ISSUE THREAD

**Issue by honguyenminh** [davidhoang05022009/fedora-post-install-script#2]
For example, "Install some CLI tools", "Install media codecs" and "Install Google's fonts"

What CLI tools? How many codecs does the script actually install? What fonts do you mean when you say "Google's fonts"? Because I don't think you're downloading everything on Google Fonts website, right? Right?

Make it clear what your script does, or else it's really hard for people to run arbitrary code they downloaded from the Internet. Seeing that it made changes to GRUB there's a chance it might, you know, brick the machine.

**Comment by hmthien050209** [comment]
OK, first of all, thanks for your feedback.
Let me update the README.md file to actually describe what it does.

> What CLI tools? How many codecs does the script actually install? 

Let me update the CLI tools list. The codecs that the script going to install is from the guide in Fedora Documentation, you can see it [here](https://docs.fedoraproject.org/en-US/quick-docs/assembly_installing-plugins-for-playing-movies-and-music/)

> What fonts do you mean when you say "Google's fonts"? Because I don't think you're downloading everything on Google Fonts website, right? Right?

Yes, it doesn't install all of the fonts on Google Fonts website. It installs all the package from dnf with the name contains "google-...-fonts" but exclude the fonts with "cjk" and broken fonts need "cjk" fonts.

> Seeing that it made changes to GRUB there's a chance it might, you know, brick the machine.

The script make a little changes to GRUB, I tested it on my main machine and VMs, it's fine, just remove the "quiet" boot screen.

**Comment by honguyenminh** [comment]
Exactly. Describe what it does like this. What command, what rpm fusion package gets installed, etc.

**Comment by hmthien050209** [comment]
OK, thanks for your feedback. I updated README.md so this issue is closed.
