### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by honguyenminh** [davidhoang05022009/fedora-post-install-script#3]
Your repo currently uses GPLv2, but it uses Dracula theme, which you stated is GPLv3. IIRC you can't use v3 code in v2 projects. Shouldn't your project be GPLv3 too?

**Comment by hmthien050209** [comment]
Let me update the license. Thanks for your feedback ^^

**Comment by hmthien050209** [comment]
I updated the license, so now this issue is closed.
